### ISSUE TITLE
GPL License Compliance Request

### ISSUE THREAD

**Issue by sej7278** [EspressifSystems/low_power_voltage_measurement#1]
Can you please provide a copy of the GPL alongside the copy of esptool.py you're bundling with your software (also how is your software licensed)?

The original author is @themadinventor from https://github.com/themadinventor/esptool

See also https://github.com/espressif/esp_iot_rtos_sdk/issues/1

**Comment by dennisdegreef** [comment]
:+1:

**Comment by zerog2k** [comment]
+1

**Comment by EspressifSystems** [comment]
We apologize for including ESPTOOL.py in this build. We have removed the file from our project. Thanks.

**Comment by sej7278** [comment]
not really the point, you should just comply to the GPL rather than remove the GPL software!

**Comment by themadinventor** [comment]
Looks like tools/add_disable_rf_cmd.py is a derivate of esptool (look at the classes ESPROM and ESPFirmwareImage).

Really, I can't see any reason why you can't just do the right thing (like adding the GPL license text and not removing copyright notices). It doesn't cost you anything, nor does it affect the licensing of your other code.

It does gain you goodwill and the advantage of having open source developers promote your product.

**Comment by sej7278** [comment]
and bin/write_flash.sh isn't going to work anymore

**Comment by EspressifSystems** [comment]
hi Fredrik, 
we apologize unreservedly on the omission of the proper license and lack of acknowledgement of use of ESPTOOL.py codes in ADD_DISABLE_RF_CMD.py. We are impressed and appreciate the great work that you have done. We have updated the copyright notice of ADD_DISABLE_RF_CMD.py to reflect your contributions. The GPL and open source licensing practices are something that we not familiar with and we appreciate the community's feedback (thanks Simon!) in guiding us through this process. We also acknowledge that we have benefited from LWIP, Contiki, and freeRTOS, etc, and benefited enormously from our interaction with the ESP8266 Community. We endeavor to provide as much information and codes as we can as go along, so as build a truly open-source platform around this chip and the next one. However, there are proprietary codes that deals with our architecture, that we have good reasons not to release. And as such, we have come to the conclusion that GPL is not suitable for our source codes. We will probably use Apache's license for the source codes that we will open source. 
Thanks.

**Comment by themadinventor** [comment]
@EspressifSystems Thanks!
While I believe that open source licensing in general will gain both Espressif and your customers in the longer term, I fully understand and respect that some parts of your platform must remain proprietary.
Espressif has already done lots in its response to the open source community.
